/*  Copyright 2025 github/anacletu
    Project: tflm-keyword-spotting-led
    Licensed under the MIT License
*/

/* model_data.h */
#ifndef MODEL_DATA_H_
#define MODEL_DATA_H_

// names generated by xxd
extern unsigned char keyword_spotting_model_0_87_int8_tflite[];  // Declaration
extern unsigned int keyword_spotting_model_0_87_int8_tflite_len; // Declaration

#endif // MODEL_DATA_H_